server:
    port: 8080
    context-path: /discovery
management:
    port: 8081
spring:
    application:
        name: eureka-server

eureka:
    # these are settings for the client that gets services
    client:
        # enable these two settings if you want discovery to work
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://localhost:8080/discovery/eureka/
        healthcheck:
              enabled: true