server:
    port: 8080
    context-path: /discovery
spring:
    application:
        name: eureka-server

eureka:
    # these are settings for the client that gets services
    client:
        # enable these two settings if you want discovery to work
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://localhost:8080/discovery/eureka/
logging:
    file: discovery.log
    level:
        org:
            springframework:
                web: DEBUG