server:
    port: 8080
    context-path: /discovery
spring:
    application:
        name: eureka-server
#Standalone Mode
eureka:
    instance:
        hostname: localhost
    # these are settings for the client that gets services
    client:
        # enable these two settings if you want discovery to work
        registerWithEureka: false
        fetchRegistry: false
        serviceUrl:
            defaultZone: http://${eureka.instance.hostname}:${server.port}/discovery/eureka/

# Peer Awareness
#eureka:
#    instance:
#        hostname: crisis.lan # hostname: crisis-etop-pc.lan
#    # these are settings for the client that gets services
#    client:
#        # enable these two settings if you want discovery to work
#        registerWithEureka: false
#        fetchRegistry: false
#        serviceUrl:
#            defaultZone: http://crisis-etop-pc.lan:${server.port}/discovery/eureka/ # hostname: crisis.lan

logging:
    file: discovery.log
    level:
        org:
            springframework:
                web: DEBUG