server:
    port: 8081
spring:
    #datasource
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/user?characterEncoding=UTF-8
        driverClassName: com.mysql.jdbc.Driver
        username: root
        password: root
        auto-commit: true
    #jpa
    jpa:
        properties:
            showSql: true
            generateDdl: true
            database: MYSQL
            hibernate:
                show_sql: true
                dialect: org.hibernate.dialect.MySQLDialect
    #spring.devtools.restart
    devtools:
        reload:
            trigger-file: .reloadtrigger
        restart:
            exclude: static/**,public/**
            enabled: true
    ioc:
        componentScan:
            basePackages: com.jeremie.spring
        jpaRepositories:
            basePackages: com.jeremie.spring.*.jpaDAO
        entityScan:
            basePackages: com.jeremie.spring.*.entity
    jpaTransactionManager:
        txAdvice:
            methodsPrefix:
                - delete
                - sava
                - add
                - update
                - sendOpen
                - sendClose
                - handle
                - batch
#log
logging:
    file: rpc-implement-http-server.log
    level:
        org:
            springframework:
                web: DEBUG
            hibernate: ERROR

eureka:
  # these are settings for the client that gets services
    client:
        # enable these two settings if you want discovery to work
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://192.168.1.240:8761/eureka/