server:
    port: 8080
spring:
    velocity:
        checkTemplateLocation: true
        properties:
                    input:
                        encoding: utf-8
                    output:
                        encoding: utf-8
    #spring.devtools.restart
    devtools:
        reload:
            trigger-file: .reloadtrigger
        restart:
            exclude: static/**,public/**
            enabled: true
    ioc:
        componentScan:
            basePackages: com.jeremie.spring
#log
logging:
    file: rpc-implement.log
    level:
        org:
            springframework:
                web: DEBUG