server:
    port: 8080
spring:
    application:
        name: rpc-client
    velocity:
        checkTemplateLocation: true
        properties:
                    input:
                        encoding: utf-8
                    output:
                        encoding: utf-8
    #spring.devtools.restart
    devtools:
        reload:
            trigger-file: .reloadtrigger
        restart:
            exclude: static/**,public/**
            enabled: true
    ioc:
        componentScan:
            basePackages: com.jeremie.spring
#log
logging:
    file: rpc-implement.log
    level:
        org:
            springframework:
                web: DEBUG

eureka:
    # these are settings for the client that gets services
    client:
        # enable these two settings if you want discovery to work
        registerWithEureka: false
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://192.168.1.104:8080/eureka/v2/